### ISSUE TITLE
forge.moltin.com gives an error 500

### ISSUE THREAD

**Issue by jpdamen** [moltin/issues#10]

**Comment by cheeryfella** [comment]
@jpdamen can you detail which end point you are hitting and also any parameters/payload information too.

**Comment by jpdamen** [comment]
Hi Ian, just buy visting the forge-backend. No api-calls. Webrequest on root https::forge.moltin.com. James said it's an issue with the cookie in my browser.

**Comment by outrunthewolf** [comment]
I've also experienced this issue. I think its something to do with session afinity on the LB's. I'm looking into it.

**Comment by outrunthewolf** [comment]
I think this looks like its fixed now.
