### ISSUE TITLE
Missing product variations matrix after modifier deletion

### ISSUE THREAD

**Issue by patrykwojtynski** [moltin/issues#11]
After variant modifier deletion all product variations are gone.

Steps to reproduce:
1. Create new product
2. Add variant modifier, for ex.: Color
3. Add at least two variations to color modifier
4. Reproduce step 3 and 4 for different modifier
5. Remove one modifier
6. Matrix is not rebuilded and empty

**Comment by outrunthewolf** [comment]
Thanks @patrykwojtynski We're looking into this now

**Comment by andrew-waters** [comment]
Hi @patrykwojtynski thanks for reporting this. I can confirm that I am able to replicate this and am working on a fix.
