### ISSUE TITLE
[Forge] Values from custom fields in 'parent' products are not propagated to the variations

### ISSUE THREAD

**Issue by aserafin** [moltin/issues#12]
Hi, 

I've added few custom fields to the `Product` flow and then assign data for them in the `parent` products. Values were not propagated neither to the existing variations nor to the ones I've created after filling data in parent products.

**Comment by aserafin** [comment]
Do you have plans on fixing it soon? It's very important for me that those custom fields values are copied to the product variations. It will allow me to avoid fetching parent product for cart items etc.

**Comment by outrunthewolf** [comment]
We're investigating how this will impact other people at the moment

**Comment by aserafin** [comment]
Sorry to push you like this, but do you know anything yet? I need to make a decision if I'm going to wait till you fix/change this or should I implement some non-trivial workarounds.

**Comment by patrykwojtynski** [comment]
Hi,
Are you still thinking about fixing it or should I create my own solution?

**Comment by andrew-waters** [comment]
Hi @patrykwojtynski, we're going to be looking at this over the next couple of weeks - it's on our issues list. If you need to bring it to your app soon, it should't be too difficult on your side to implement, but if you'd prefer to wait for a native implementation, then it may be worth holding fire for a little while.

**Comment by andrew-waters** [comment]
@patrykwojtynski and @aserafin, this should be resolved in a release last Friday so I'm going to close this issue. If you have any issues, please let us know. Thanks for reporting.
