### ISSUE TITLE
Unable to Login to Forge, error: Missing required parameter refresh_roken

### ISSUE THREAD

**Issue by sidm** [moltin/issues#17]
Steps to reproduce:
- Attempt to login to https://forge.moltin.com/login using a valid e-mail and password combination

![screen shot 2015-12-04 at 11 17 57 am](https://cloud.githubusercontent.com/assets/728604/11594581/e1eea012-9a78-11e5-8ce0-16b4226ecf6e.png)

**Comment by sidm** [comment]
So I tried it in an incognito window in Chrome and I was able to login, seems to be an issue client-side with my cookies. May be an isolated issue specific to me?

**Comment by jfmengels** [comment]
This bug happens to me too sometimes. Clearing my cookies makes it work again.

**Comment by AJSturrock** [comment]
This is a known issue which we're taking a look into. You can also visit https://forge.moltin.com/logout to temporarily fix the issue.
