### ISSUE TITLE
Bug: API always returns GMT time zone

### ISSUE THREAD

**Issue by nabilfreeman** [moltin/issues#20]
In Forge, you can set your local time zone, but it doesn't affect the API.

This is a problem for customers who are not in the UK.

Examples:

When generating email templates, the `created_at` and `updated_at` fields are useless for foreign customers.

When handling API requests, foreign customers must write their own middleware to convert the times.

**Comment by nabilfreeman** [comment]
hey guys, have you seen this?

**Comment by nabilfreeman** [comment]
Another bump... anyone home? :fist: 

Suggested implementation: Dropdown here. I bet the pretty printing function you guys are using takes a time zone parameter so I doubt it would be difficult to implement.

<img width="920" alt="screen shot 2016-02-26 at 22 13 02" src="https://cloud.githubusercontent.com/assets/2470659/13354477/3c5db7be-dcd6-11e5-8078-c42eba3449f9.png">

**Comment by zot24** [comment]
Hi Nabil!

We have being thinking about your issue and it make sense, we are not sure yet about how it's the best way to implement this feature, if use the store location (time zone) as you suggested or add that option along side emails settings.

Anyhow we are using [twig](http://twig.sensiolabs.org/doc/filters/date.html) to render the email templates so technically you could use `twig` `timezone` filter to alter the date, like shown below:

```
{{ post.published_at|date("m/d/Y", "Europe/Paris") }}
```

Give it a try and let us know :smile: 

btw sorry for the late answer

**Comment by nabilfreeman** [comment]
Thanks for the reply Israel :smile: 

I didn't know Twig had a built-in date filter! Thanks for bringing that to my attention. I fixed the emails using that, so thanks very much.

For other API usages, it would still be really useful to have a regional formatted time, or a raw UNIX timestamp (or both). It eliminates the risk of a parsing error outside of the Moltin API.

Thanks again for the help :raised_hands:

**Comment by zot24** [comment]
Your welcome @nabilfreeman glad you find a solution :)

Closing it now
