### ISSUE TITLE
Responsive Forge dashboard UI

### ISSUE THREAD

**Issue by nichoth** [moltin/issues#21]
UI needs to be responsive for small screens. The bottom of the menu is hidden and it doesn't scroll.
![screen shot 2016-03-04 at 4 38 29 pm](https://cloud.githubusercontent.com/assets/5776508/13544211/5f8253f6-e228-11e5-951e-4a3b52347022.png)

**Comment by DamianKidd** [comment]
Thank you for your feedback. We will be releasing a new **moltin** forge later this year.
