### ISSUE TITLE
Variants and Modifiers are either confusing or don't function as expected

### ISSUE THREAD

**Issue by pveller** [moltin/issues#32]
Products in my catalog vary by `size` or `color` or both. One example that I am looking at right now has only three variants (`S`, `M` and `L` size). The product always comes in `Blue` color. I created one product and then created two modifiers - `color` and `size`. Then I created a `Blue` variant and three size variants. I ended up with four `is_variant` products created. I would expect a *product* of 3x1 which is sill 3. As far as I understand you guys create these variants upon me calling the endpoint and you don't re-shuffle them as I create more. I must note that I create everything via the API. Maybe the right solution is the bulk import API that comes in v2 (I hope)? 

Also, I see that you guys add the variation name to the product's base SKU. How can I turn that off? I see that I can actually send a `sku` attribute along with the `mod_price` for the variant. It's not documented but it works :) You still add the variation `title` to it after the `_` though. Can it be turned off?

Also, haven't tried it yet but I wonder. If I define extra attributes on the product's `Flow` and then send them along for each variant - will you *see* that and store it on the `is_variant`? You see, in my catalog the majority of information is on the variant, not the product. And in your data model it seems that it's the other way around. A good **data modeling* reference with example would be a good idea for the products/modifiers/variants section. Basically a few example of different types of catalog structures implemented in Moltin.

**Comment by andrew-waters** [comment]
Hi @pveller,

> I would expect a product of 3x1 which is sill 3.

You should actually have 4 because there is also a "parent" product - how many are you seeing and if possible, can you show us the response.

> As far as I understand you guys create these variants upon me calling the endpoint and you don't re-shuffle them as I create more.

As you add variation options to the parent product, we will dynamically create more. For example, if you add `Red` to the colours you should have 6 "child" products as we generate this dynamically.

**Comment by pveller** [comment]
Hi @andrew-waters, I posted yesterday on Slack:

https://moltinhub.slack.com/files/pveller/F2LG26ASJ/pasted_image_at_2016_10_07_12_05_am.png
https://moltinhub.slack.com/files/pveller/F2LG7PQ2H/pasted_image_at_2016_10_07_12_05_am.png

@AJSturrock  asked me if I:

```
1. Create base product
2. Create modifiers (size & color etc..)
3. Create variants for each modifier
```

And I answered yes, exactly, in that order using the APIs, not the Forge dashboard

**Comment by andrew-waters** [comment]
Does the same thing happen when creating this set of products using Forge?

**Comment by pveller** [comment]
I haven't tried using Forge. I sure can but I know I will be creating the catalog via the API anyway as I am scripting it from the CSV files (I am actually creating a sample store using the Adventure Works dataset. Will share my scripts once I am through with it as it might be useful for others too). 

I will give a try later today and let you know guys.

**Comment by andrew-waters** [comment]
I'm just wondering if you can do it that way because forge uses the API as well (there's nothing magic going on), so I'd like to see if it's an API issue or something in the order of the calls. Would be great to see if it works through Forge and if it does we can take a look at the calls you're making to figure out what's going on.

**Comment by pveller** [comment]
Forge does the right thing and now I am thinking it *is* indeed order and what's even more likely - the **timing** of it. I run it all asynchronously with `Promise`s so the variants for a given modifier are created in parallel. Kind of. Here's an excerpt from my `Promise`s chain that creates variants for all previously created modifiers (in my case `size` and `color`).

`mods` is the array of the modifiers created on the previous step. I `map` them down to the list of their values (like `blue` or `S`) and for each value I create a variation in Moltin. The `i` is the current inventory item that I read from the CSV files. Think of it as a parent product in context.

```javascript
.then(mods => {
            return Promise.all(mods.map(mod => {
                return new Promise((resolve, reject) => {
                    Promise.all(mod.values.map(value => {
                        const variant = i.variants.find(v => v[mod.title] === value);
                        if (!variant) {
                            throw `Can't find a variant for ${p.name} with ${mod.title} equal to ${value}`;
                        }
                        return new Promise((resolve, reject) => {
                            moltin.Authenticate(function() {
                                moltin.Variation.Create(mod.productId, mod.id, {
                                    title: value,
                                    sku: variant.sku // this works btw on the variations
                                },
                                function(result){
                                    // enhance for the next then() in the chain
                                    resolve({
                                        id: result.id,
                                        variantId: variant.id,
                                        productId: variant.model,
                                        images: variant.images
                                    });
                                }, 
                                function(error, details) {
                                    console.error(details);
                                    reject(details);
                                });
                            });
                        });
                    })).then(values => {
                        resolve(_.flatten(values));
                    });
                });
            }));
        })
```

**Comment by pveller** [comment]
In general, since your API is also asynchronous, the only way to sequence the creation of the variants would be to chain the callbacks. I would *promisify* your endpoints and create a chain in a loop or something. I will try that next. Will keep you posted!

**Comment by andrew-waters** [comment]
Thanks for the update @pveller, I'll close this as an implementation issue rather than an API issue - if you find anything that requires it to be reopened please do so here.

**Comment by pveller** [comment]
It would be nice if I could trigger the matrix rebuild via the API. Sequencing variants creation is not the best answer I think. See what I mean? And I will let you know if sequencing helped. Thanks!

**Comment by pveller** [comment]
@andrew-waters, I can confirm that sequencing variations creation helps but this is something that needs to be clearly articulated int he docs I think. The API is asynchronous so requiring to chain the creation is an important aspect of how the matrix is created behind the scene. Better yet though allow to trigger the matrix rebuild and then I can parallel out all variations. 

You have already seen how I am creating the variations. Here's how I sequenced it:

```javascript
.then(mods => {
    const variations = [];
    const chained = mods.reduce((chain, mod) => {
        return mod.values.reduce((chain, value) => {
            return chain.then(() => addVariant(
                mod, 
                value, 
                i.variants.find(v => v[mod.title] === value), 
                variations));
        }, chain);
    }, Promise.resolve());
    
    return chained.then(() => Promise.resolve(variations));
})
```

And my log clearly shows a sequential order:

```
Adding a variant for [object Object] - Blue
Variant for [object Object] - Blue added
Adding a variant for [object Object] - S
Variant for [object Object] - S added
Adding a variant for [object Object] - M
Variant for [object Object] - M added
Adding a variant for [object Object] - L
Variant for [object Object] - L added
```
