### ISSUE TITLE
Enconding issues in Cart.Contents

### ISSUE THREAD

**Issue by aserafin** [moltin/issues#4]
I'm calling Cart.Contents in js sdk and it looks like all special characters in variation title, name, description come back with weird encoding but they look fine in the main product. Screenshot attached
<img width="949" alt="screenshot 2015-10-29 10 07 18" src="https://cloud.githubusercontent.com/assets/778667/10814242/f82afd1e-7e24-11e5-90ca-1a5b46e10edc.png">

**Comment by outrunthewolf** [comment]
Acknowledged.

We'll investigate now.

**Comment by Jmz** [comment]
Hi @aserafin 

I'm having a look into this issue now. How did you initially create this product (forge, direct API requests an SDK etc.)?

**Comment by aserafin** [comment]
Via Forge - we created products, then added some modifiers and in the product variations that created automatically we saw the issue

**Comment by Jmz** [comment]
Could you check the URL you're hitting to get the cart contents? I just need to verify which version of the API you're getting results from.

**Comment by aserafin** [comment]
sure, it's `https://api.molt.in/v1/carts/undefined?` the `undefined` also worries me a little as it seems that cart isn't getting it's identifier although your docs don't specify that I should call anything special for cart to get id...

**Comment by Jmz** [comment]
Technically with that request you're looking for carts with the ID `undefined`, which means all users on your site would be using the same cart. There was an update to the SDK pushed yesterday which will automatically generate the cart ID if one doesn't exist.

The strings are HTML encoded in the database but it looks like the cart data isn't being decoded when it is returned. I'll add a fix for this.

**Comment by aserafin** [comment]
Hmm... I've probably didn't update your library - will check with the newest version, but from what I can see in the inspector I have mCart cookie set but the request is still sent with `undefined`
<img width="1333" alt="screenshot 2015-10-29 18 04 22" src="https://cloud.githubusercontent.com/assets/778667/10826008/f123ef38-7e67-11e5-81cd-723c9b4ebb9b.png">

**Comment by aserafin** [comment]
It looks like I'm getting SDK from https://js.moltin.com/v1 so I should have the latest one right?

**Comment by aserafin** [comment]
Hmm... Isn't this a problem:

    if (!reset && !id && this.m.Storage.get('mcart') !== null) {
      return this.m.Storage.get('mcart');
    }

in the `Cart.Identifier` function? If the id is in cookies already you will just return it but not set `this.cartId` so in all next calls it ends up being `undefined`?

**Comment by Jmz** [comment]
It looks like there are a couple of different issues here. I'll ask one of the other developers to get back to you on the SDK issues while I look at the original encoding issue. 

Do you have a temporary version of the site we can access? You can DM me a link on the Moltin Slack channel if you'd rather not post it here.

**Comment by aserafin** [comment]
No sorry, everything is still on localhost. Pretty sure about the reason of the cart identifier issue though - could you maybe prioritize it as this is kind of big problem with potentially easy fix :)

**Comment by outrunthewolf** [comment]
Please make sure any other issues are reported in new threads so we can track them better @aserafin
