### ISSUE TITLE
[JS-SDK] Cart.Contents modifiers array contains incorrect data

### ISSUE THREAD

**Issue by aserafin** [moltin/issues#8]
In the response from `Cart.Contents` I'm getting wrong data back in the `modifiers` array (it's correct in the `modifier` object).

<img width="358" alt="screenshot 2015-10-29 16 54 14" src="https://cloud.githubusercontent.com/assets/778667/10841555/ab747b5a-7eea-11e5-858e-ebd78f824963.png">

As you can see on the screenshot the size and color are messed up though checking the ids in the forge it looks like they are correct in the `modifier` object above.

**Comment by outrunthewolf** [comment]
JS can't handle 64bit ints properly so it rounds them. The key (id) will need to be a string.

We'll issue a patch for it.

**Comment by aserafin** [comment]
Hmm... not sure I follow - the `modifier` object contains correct data according to what I check in forge (modifier/variant id pairs). The `modifiers` array looks wrong: in `modifiers[2].data.title` I have `Color` and in the `modifiers[2].var_title` I have `L` when it should be `Green`. This is the issue with integers you are talking about?

**Comment by outrunthewolf** [comment]
OK. I see what you mean now.

**Comment by andrew-waters** [comment]
I've been able to duplicate this outside of JS, so can confirm it's an issue within the API itself. I'm taking a look at it now for you @aserafin

**Comment by outrunthewolf** [comment]
:+1:
