### ISSUE TITLE
Broken product variation title after variation editing

### ISSUE THREAD

**Issue by patrykwojtynski** [moltin/issues#9]
After editing one of `variations` (via forge, original title: 'I'd tap that') all titles changed to this:
<img width="1202" alt="zrzut ekranu 2015-10-30 o 14 38 44" src="https://cloud.githubusercontent.com/assets/8479700/10847014/f5538cd8-7f13-11e5-9849-f8b2a7503043.png">

**Comment by outrunthewolf** [comment]
Related to https://github.com/moltin/issues/issues/4

**Comment by cheeryfella** [comment]
Hi patrykwojtynksi,

Thank you for raising this ticket. I am looking into this now - it appears that some recursive html encoding is going on. I will update you as soon as I have some relevant information.

**Comment by outrunthewolf** [comment]
I assume these were the steps:

 - Created a product
 - Created a couple of languages
 - Added a couple of multi-lingual titles to the product
 - Created a modifier (type=variant) on the product
 - Created a variation on the modifier and see what happens to the title

**Comment by patrykwojtynski** [comment]
Hi, thank you for the quick reply. 

What I have done:
1. Created a product
2. Created a modifier on the product
3. Created a variations on the modifier (this added one '&quot' to every variation title)
4. Edited variation price and this added a lot z&quot`s to every title

**Comment by patrykwojtynski** [comment]
Sorry I missclick on my phone. Still open.

**Comment by outrunthewolf** [comment]
:+1: 
 Thanks for the help with steps

**Comment by outrunthewolf** [comment]
We have a patch for this going live today.

Some of your existing items may still be affected. Ping me if you need help getting them updated
